docs/examples.md, docs/glossary.md, src/__tests__/diamond.ts, src/__tests__/index.ts, src/__tests__/perf.ts, src/examples/counter.test.ts, src/examples/todoapp/src/features/app/AddTodo.tsx, src/examples/todoapp/src/features/app/TodoList.tsx, src/examples/todoapp/src/features/app/VisibilityFilters.tsx, src/examples/todoapp/src/features/app/domain.tsx, src/examples/todoapp/src/features/auth/index.tsx, src/examples/todoapp/src/index._test_.tsx, src/examples/todoapp/src/index.tsx, src/index.ts
=> core/all/mod: declareAtom, declareAction

src/__tests__/index.ts, src/index.ts
=> fix(core): improve undefined state errors

packages/react/README.md, packages/react/package.json, packages/react/src/index.ts, packages/react/tsconfig.json
=> feat(react): add package

README.md, docs/README.md
=> docs: add packages table

packages/react/package.json
See https://github.com/SamVerschueren/listr/pull/61#issuecomment-302147242
=> fix(react): correct package.json for npm links

packages/core/package.json, packages/react/package.json
fix #66 
See solution: https://github.com/facebook/create-react-app/issues/3237#issuecomment-354554624
=> fix broken project builds with mjs modules

packages/core/.size-limit.json, packages/core/package.json
=> ci(core): add size-limit #6

README.md, docs/README.md, packages/core/README.md, packages/react/README.md
=> docs: v1.0.0 release schedule

packages/core/README.md, packages/react/README.md
=> change logo url for packages

docs/faq.md
Thank you for the great library, I've made a few minor edits. Hope it still carries the same idea as you initially intended. Any feedback is welcome =)
=> A few minor FAQ tweaks

packages/core/src/__tests__/redux/atom subscribe.ts, packages/core/src/__tests__/redux/store subscribe.ts, packages/core/src/createStore.ts, packages/core/src/shared.ts
Implement redux subscription tests, make subscribers immutable. #13
=> Redux compatible

package.json, packages/babel-plugin/README.md, packages/babel-plugin/babel-plugin.js, packages/babel-plugin/package.json, packages/babel-plugin/test/fixtures/combine/code.js, packages/babel-plugin/test/fixtures/combine/output.js, packages/babel-plugin/test/fixtures/declareAction/code.js, packages/babel-plugin/test/fixtures/declareAction/output.js, packages/babel-plugin/test/fixtures/declareAtom/code.js, packages/babel-plugin/test/fixtures/declareAtom/output.js, packages/babel-plugin/test/fixtures/map/code.js, packages/babel-plugin/test/fixtures/map/output.js, packages/babel-plugin/test/index.spec.js
automate name generation for `declareAtom` and `declareAction`
=> feat(babel-plugin): implement #87

package-lock.json, package.json, packages/core/src/index.ts, packages/core/src/shared.ts, packages/debug/README.md, packages/debug/babel.config.js, packages/debug/package.json, packages/debug/src/genIdFromLine.ts, packages/debug/src/index.ts, packages/debug/test/index.ts, packages/debug/tests/index.ts, packages/debug/tsconfig.json, tsconfig.json
=> Add @reatom/debug package

packages/observable/README.md, packages/observable/babel.config.js, packages/observable/package.json, packages/observable/src/index.ts, packages/observable/test/index.ts, packages/observable/tsconfig.json
=> Implement @reatom/observable

packages/core/package.json
=> fix(core): add sideEffects: false

docs/README.md
=> docs: fix link to "diamond problem"

packages/core/src/__tests__/index.ts, packages/core/src/benchmark/lists/redux.ts, packages/core/src/createStore.ts, packages/core/src/declareAction.ts, packages/core/src/declareAtom.ts, packages/core/src/shared.ts, packages/core/tsconfig.json
=> refactor(core): typings and code cleanup

docs/styles.css
=> chore: fix stars overlap

packages/core/src/__tests__/index.ts, packages/core/src/createStore.ts, packages/core/src/declareAction.ts, packages/core/src/declareAtom.ts, packages/core/src/kernel.ts
=> Refactoring

docs/_sidebar.md, docs/guides/migration-from-redux.md
=> docs: migration from Redux

docs/examples.md
=> docs: Update examples.md

CONTRIBUTING.md
Add example commit message to avoid confusion around square vs round brackets
=> docs: add example commit messages

.github/workflows/commitlint.yml
=> ci: add commitlint

packages/core/package.json
Fix for commit c8dbfd7 (splitting index.ts into multiple files).
I suspect this was not changed during files restructuring.
=> fix(core): include all sources in core npm package

packages/react/package.json, packages/react/tests/index.test.tsx, packages/react/tsconfig.json
=> refactor(react): move tests out of the src directory

docs/guides/migration-from-redux.md
=> docs: #202 fix redux-saga example

docs/packages/reatom-react.md
=> docs: reatom-react.md spelling and grammar

package-lock.json, packages/react/package.json, packages/react/src/index.ts
=> fix(react): #209 typings

packages/react/src/index.ts, packages/react/tests/index.test.tsx
fixes #238 
non-breaking change
=> feat(react): export context provider component

.huskyrc, package-lock.json
=> ci: run prettier before commit

docs/README.md
=> fix broken link to `diamond problem`

docs/README.md
=> docs: goals / add framework-agnostic

packages/react/src/index.ts
=> refactor(react): improve type inference for useAction hook

packages/react/src/index.ts, packages/react/tests/index.test.tsx
=> feat(react): implement createAtomHook and createActionHook

packages/core/src/declareAtom.ts, packages/core/src/shared.ts, packages/core/tests/index.test.ts
=> fix(core): fix reducers result equality

packages/core/src/createStore.ts, packages/core/src/declareAtom.ts, packages/core/src/shared.ts, packages/core/tests/index.test.ts
=> fix(core): fix symbol ignoring in initial atoms

packages/core/src/declareAtom.ts
=> fix(core): improve type inference with TypeScript 3.5

packages/core/src/kernel.ts
=> fix(core): fix type of payload in action

packages/react/src/index.ts, packages/react/tests/index.test.tsx
=> fix(react): update state and act wrapper if store instance has changed

packages/debug/src/genIdFromLine.ts, packages/debug/test/index.ts
=> fix(debug): name as a symbol

docs/README.md
Concurrency problems? — https://github.com/sergeysova/effector-ssr
=> Remove concurrency problems with Effector on SSR from Readme

docs/guides/migration-from-redux.md
=> docs: add redux-observable migration section
